export { SizeManager2D } from './SizeManager2D'
export type { SizeManager2DOptions } from './SizeManager2D'
export { SizeManager3D } from './SizeManager3D'
export type { SizeManager3DOptions } from './SizeManager3D'
export { computeDashboardActualSize } from './dashboardSize'
export type { DashboardSizeInput, DashboardSizeResult } from './dashboardSize'
